services:
  velocity-mongo:
    image: mongo:8.0
    volumes:
      - ./mongo:/data/db
    ports:
      - 27018:27017

  credentialinghub:
    image: ghcr.io/velocitynetworkfoundation/credentialinghub:testnet
    env_file:
      - .env
    ports:
      - 8080:3000
    restart: on-failure
    depends_on:
      - velocity-mongo

